### ISSUE TITLE
Unable to get this working

### ISSUE THREAD

**Issue by verisgit** [ccorderor/huawei-sun2000-modbus-mqtt#1]
Hi there,

Trying to get this working. I also have a SUN2000-5KTL-L1. I have a vanilla RPI4 with Rabian OS Lite. I've installed your docker image and changed the config as my Sun2000 IP is 192.168.200.1:6607 (port 502 isn't used in the latest firmware).

When I try run the app I get the following error:
`sudo docker run huawei-solar
Traceback (most recent call last):
  File "huaweisolar.py", line 2, in <module>
    from huawei_solar import HuaweiSolar
  File "/usr/local/lib/python3.8/site-packages/huawei_solar/__init__.py", line 6, in <module>
    from .bridge import HuaweiSolarBridge  # noqa
  File "/usr/local/lib/python3.8/site-packages/huawei_solar/bridge.py", line 15, in <module>
    from huawei_solar.huawei_solar import AsyncHuaweiSolar, Result
  File "/usr/local/lib/python3.8/site-packages/huawei_solar/huawei_solar.py", line 35, in <module>
    from .registers import REGISTERS, RegisterDefinition
  File "/usr/local/lib/python3.8/site-packages/huawei_solar/registers.py", line 216, in <module>
    class TimeOfUseRegisters(RegisterDefinition):
  File "/usr/local/lib/python3.8/site-packages/huawei_solar/registers.py", line 228, in TimeOfUseRegisters
    ) -> list[LG_RESU_TimeOfUsePeriod]:
TypeError: 'type' object is not subscriptable
`

Any ideas or things I could troubleshoot?

**Comment by sammyke007** [comment]
Same error over here

**Comment by carlioth** [comment]
You need to pin the version. PR created for the fix here: https://github.com/ccorderor/huawei-sun2000-modbus-mqtt/pull/2/files

**Comment by ccorderor** [comment]
PR merged.
Thank you @carlioth 
Can you please check that now it is working correctly @verisgit ?

**Comment by shakisha** [comment]
@ccorderor  on my side it have got almost the same issue: 

Traceback (most recent call last):
  File "/home/pi/data/huawei.py", line 2, in <module>
    from huawei_solar import HuaweiSolar
ImportError: cannot import name 'HuaweiSolar' from 'huawei_solar' (/usr/local/lib/python3.9/dist-packages/huawei_solar/__init__.py)

**Comment by subtrEM** [comment]
@shakisha works with huawei_solar v 1.2.0 (i had to use `pip3 install --force-reinstall -v "huawei-solar==1.2.0"` to get the right version) - unfortunately, as this version has been superseded by the redesigned and maintained v2
